name: sammy
favicon: null
layout_spectrum: 0.7428332602139562
typography_spectrum: 0.8140468401834369
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.18081926321610808
  lightness: 0.28963570250198245
  saturation: 0.4059652481228113
  rhythmicContrast: 0.18935183016583323
purpose: []
